<!DOCTYPE html>
<html><head>
<title>href.li</title>
<meta http-equiv="Refresh" content="0; url=https://files.teamspeak-services.com/releases/client/3.6.0/TeamSpeak3-Client-linux_amd64-3.6.0.run" />
<meta name="referrer" content="no-referrer" />
<script type="text/javascript">
/* <![CDATA[ */
window.location.replace( "https:\/\/files.teamspeak-services.com\/releases\/client\/3.6.0\/TeamSpeak3-Client-linux_amd64-3.6.0.run" + window.location.hash );
/* ]]> */
</script>
</head>
<body><p>Redirecting..<br /><a href="https://files.teamspeak-services.com/releases/client/3.6.0/TeamSpeak3-Client-linux_amd64-3.6.0.run">https://files.teamspeak-services.com/releases/client/3.6.0/TeamSpeak3-Client-linux_amd64-3.6.0.run</a></p></body></html>